export enum UserStatus {
  EMAIL_ACTIVATION_PENDING = 'EMAIL_ACTIVATION_PENDING',
  ACCOUNT_VALIDATION_PENDING = 'ACCOUNT_VALIDATION_PENDING',
  ACTIVE = 'ACTIVE',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  INACTIVE = 'INACTIVE',
  CLOSED = 'CLOSED',
}

export enum UserRoles {
  SA = 'SA',
  ADMINISTRATOR = 'ADMINISTRATOR',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  PROFESSIONAL = 'PROFESSIONAL',
  PATIENT = 'PATIENT',
  TECHNICIAN = 'TECHNICIAN',
  DIRECTIVE = 'DIRECTIVE',
  USER = 'USER',
}

export enum RestrictedRoles {
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  PROFESSIONAL = 'PROFESSIONAL',
  PATIENT = 'PATIENT',
  TECHNICIAN = 'TECHNICIAN',
  DIRECTIVE = 'DIRECTIVE',
  USER = 'USER',
}
